server:
  port: 8280
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/officenter
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

